### ISSUE TITLE
Function results can set `FusionCacheEntryOptions.Duration`

### ISSUE THREAD

**Issue by JoeShook** [jodydonetti/ZiggyCreatures.FusionCache#23] opened 2021-06-18 18:53 UTC
I have a use case where the returned data from a function passed to FusionCache contains the TTL (time to live), kind of like a DNS query answer.  I would like to use that result to set the duration from calls like `GetOrSetAsync` .  

I see `MemoryOptionsModifier` was something that might have been the way to go but the property is marked obsolete and not wired in.  

Of course I can call TryGetAsync and then SetAsync in the meantime.  @jodydonetti  curious about your thoughts on this?

**Comment by jodydonetti** [comment] 2021-06-20 20:36
> I have a use case where the returned data from a function passed to FusionCache contains the TTL (time to live), kind of like a DNS query answer. I would like to use that result to set the duration from calls like `GetOrSetAsync` .

Yes, this is an absolutely reasonable requirement, so much so that other people alredy asked for it and is already in my backlog 😄 (see #17)

> I see `MemoryOptionsModifier` was something that might have been the way to go but the property is marked obsolete and not wired in.

Yes, because it was an early experiment into that kind of feature, but the split between memory and distributed modifiers was not the greatest idea. Since I want to do something better, and the right design is not that straightforward, I postponed that decision and kept playing with different designs to strike the right balance.

I'm closing this since it is basically a duplicate of #17 but I hope to be able to have news on this feature quite soon!

**Closed** 2021-06-20 20:36 UTC
Labels: duplicate, enhancement

**Comment by JoeShook** [comment] 2021-06-21 20:12
This sounds great.  I figured my request was buried inside one of the other issues.  Thanks.

**Comment by jodydonetti** [comment] 2021-06-27 10:54
Hi @JoeShook !
I've finally found some time to put down in words a couple of proposals for this here #24 !
I would be really interesed in knowing what you think.
